version: '3.8'
services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: nocountry
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auction
    ports:
      - 5432:5432
